import {
    pgTable,
    uuid,
    text,
    timestamp,
    integer,
    bigint,
    boolean,
    doublePrecision,
    jsonb,
    index,
    uniqueIndex,
    unique,
    check,
    foreignKey,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import type { CustomFields } from "@sendlit/api-contract";
import { genId, genPublicId } from "./id";

/** A `CHECK` enforcing that a public-id column always carries its resource's
 * prefix (`cnt_`, `seq_`, ...) — defense in depth alongside `genPublicId()`,
 * so a malformed value can never be inserted even by code that bypasses it
 * (a script, a future migration, direct SQL). */
function publicIdCheck(name: string, column: any, prefix: string) {
    // The pattern must be inlined as a literal, not a bound parameter —
    // drizzle-kit emits `CHECK` clauses verbatim into the migration SQL file,
    // which is replayed later with no params to bind against (`$1` would be
    // dangling, invalid SQL). `prefix` is always a trusted internal literal
    // (never user input), so `sql.raw` here is safe.
    return check(name, sql`${column} ~ ${sql.raw(`'^${prefix}_'`)}`);
}

/**
 * ID convention used across every table in this schema:
 *
 * - `id` is an internal-only UUIDv7 surrogate primary key. It is what every
 *   foreign key in this file references, and it is never returned by any
 *   REST/MCP response (see `utils/public.ts`). UUIDv7 keeps inserts roughly
 *   time-ordered, unlike UUIDv4/`gen_random_uuid()`, which scatters inserts
 *   randomly across the primary key's B-tree.
 * - `<domain>_id` (e.g. `contact_id`, `sequence_id`) is the public-facing
 *   identifier: `<prefix>_<24 random chars>`, generated by `genPublicId()`.
 *   It's the only ID ever exposed to API/MCP consumers, and the only one
 *   ever accepted back from them to address a row.
 *
 * Every foreign key in this file — including on the event/log tables
 * (`ongoing_sequences`, `email_deliveries`, `email_events`, `rules`) and
 * `contact_custom_field_values` — references the target row's internal `id`,
 * with `ON DELETE CASCADE`. Write paths that only have the public id on hand
 * (tracking pixels, rule processing) resolve public → internal id first.
 */

/** Durable customer/administration boundary above teams. */
export const organizations = pgTable(
    "organizations",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        organizationId: text("organization_id")
            .notNull()
            .unique()
            .$defaultFn(() => genPublicId("org")),
        name: text("name").notNull(),
        status: text("status").notNull().default("active"),
        createdAt: timestamp("created_at", { withTimezone: true })
            .notNull()
            .defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true })
            .notNull()
            .defaultNow(),
    },
    (table) => ({
        organizationIdCheck: publicIdCheck(
            "organizations_organization_id_check",
            table.organizationId,
            "org",
        ),
        statusCheck: check(
            "organizations_status_check",
            sql`${table.status} IN ('active', 'suspended', 'closed')`,
        ),
    }),
);

/** Better Auth's default human identity model and table. */
export const user = pgTable("user", {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    email: text("email").notNull().unique(),
    emailVerified: boolean("email_verified").notNull().default(false),
    image: text("image"),
    defaultOrganizationId: uuid("default_organization_id").references(
        () => organizations.id,
        { onDelete: "set null" },
    ),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
});

/** Explicit organization authorization; authentication alone grants nothing. */
export const organizationMembers = pgTable(
    "organization_members",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        organizationId: uuid("organization_id")
            .notNull()
            .references(() => organizations.id, { onDelete: "cascade" }),
        userId: text("user_id")
            .notNull()
            .references(() => user.id, { onDelete: "restrict" }),
        role: text("role").notNull(),
        createdAt: timestamp("created_at", { withTimezone: true })
            .notNull()
            .defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true })
            .notNull()
            .defaultNow(),
    },
    (table) => ({
        organizationUserIdx: uniqueIndex(
            "organization_members_organization_id_user_id_idx",
        ).on(table.organizationId, table.userId),
        roleCheck: check(
            "organization_members_role_check",
            sql`${table.role} IN ('owner', 'admin', 'member')`,
        ),
    }),
);

/** Immutable operational record for organization administration and
 * integration-driven lifecycle changes. It intentionally stores references
 * rather than secrets or raw API keys. */
export const organizationAuditEvents = pgTable(
    "organization_audit_events",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        organizationId: uuid("organization_id")
            .notNull()
            .references(() => organizations.id, { onDelete: "restrict" }),
        actorType: text("actor_type").notNull(), // user|organization_key|team_key|system
        actorId: text("actor_id"),
        action: text("action").notNull(),
        teamId: uuid("team_id"),
        espConfigId: uuid("esp_config_id"),
        espGrantId: uuid("esp_grant_id"),
        metadata: jsonb("metadata").notNull().default({}),
        createdAt: timestamp("created_at", { withTimezone: true })
            .notNull()
            .defaultNow(),
    },
    (table) => ({
        organizationCreatedIdx: index(
            "organization_audit_events_organization_id_created_at_idx",
        ).on(table.organizationId, table.createdAt),
        teamCreatedIdx: index(
            "organization_audit_events_team_id_created_at_idx",
        ).on(table.teamId, table.createdAt),
    }),
);

/** Team/workspace and email-data boundary. Every team belongs to one org. */
export const teams = pgTable(
    "teams",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        teamId: text("team_id")
            .notNull()
            .unique()
            .$defaultFn(() => genPublicId("team")),
        organizationId: uuid("organization_id")
            .notNull()
            .references(() => organizations.id, { onDelete: "restrict" }),
        externalId: text("external_id"),
        provisioningRequestHash: text("provisioning_request_hash"),
        name: text("name").notNull(),
        status: text("status").notNull().default("active"),
        createdAt: timestamp("created_at", { withTimezone: true })
            .notNull()
            .defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true })
            .notNull()
            .defaultNow(),
    },
    (table) => ({
        teamIdCheck: publicIdCheck("teams_team_id_check", table.teamId, "team"),
        organizationExternalIdIdx: uniqueIndex(
            "teams_organization_id_external_id_idx",
        )
            .on(table.organizationId, table.externalId)
            .where(sql`${table.externalId} IS NOT NULL`),
        idOrganizationIdx: unique("teams_id_organization_id_unique").on(
            table.id,
            table.organizationId,
        ),
        statusCheck: check(
            "teams_status_check",
            sql`${table.status} IN ('active', 'sending_suspended', 'archived')`,
        ),
    }),
);

/** Team membership is independent from organization membership. */
export const teamMembers = pgTable(
    "team_members",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        teamId: uuid("team_id")
            .notNull()
            .references(() => teams.id, { onDelete: "cascade" }),
        userId: text("user_id")
            .notNull()
            .references(() => user.id, { onDelete: "restrict" }),
        role: text("role").notNull().default("member"),
        createdAt: timestamp("created_at", { withTimezone: true })
            .notNull()
            .defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true })
            .notNull()
            .defaultNow(),
    },
    (table) => ({
        teamUserIdx: uniqueIndex("team_members_team_id_user_id_idx").on(
            table.teamId,
            table.userId,
        ),
        roleCheck: check(
            "team_members_role_check",
            sql`${table.role} IN ('admin', 'member')`,
        ),
    }),
);

/** Better Auth's remaining default core models/tables. */
export const session = pgTable(
    "session",
    {
        id: text("id").primaryKey(),
        expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
        token: text("token").notNull().unique(),
        createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
        ipAddress: text("ip_address"),
        userAgent: text("user_agent"),
        userId: text("user_id")
            .notNull()
            .references(() => user.id, { onDelete: "cascade" }),
    },
    (table) => ({
        userIdIdx: index("auth_session_user_id_idx").on(table.userId),
    }),
);

export const account = pgTable(
    "account",
    {
        id: text("id").primaryKey(),
        accountId: text("account_id").notNull(),
        providerId: text("provider_id").notNull(),
        userId: text("user_id")
            .notNull()
            .references(() => user.id, { onDelete: "cascade" }),
        accessToken: text("access_token"),
        refreshToken: text("refresh_token"),
        idToken: text("id_token"),
        accessTokenExpiresAt: timestamp("access_token_expires_at", {
            withTimezone: true,
        }),
        refreshTokenExpiresAt: timestamp("refresh_token_expires_at", {
            withTimezone: true,
        }),
        scope: text("scope"),
        password: text("password"),
        createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
    },
    (table) => ({
        userIdIdx: index("auth_account_user_id_idx").on(table.userId),
    }),
);

export const verification = pgTable(
    "verification",
    {
        id: text("id").primaryKey(),
        identifier: text("identifier").notNull(),
        value: text("value").notNull(),
        expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
        createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
    },
    (table) => ({
        identifierIdx: index("auth_verification_identifier_idx").on(
            table.identifier,
        ),
    }),
);

export const jwks = pgTable("jwks", {
    id: text("id").primaryKey(),
    publicKey: text("public_key").notNull(),
    privateKey: text("private_key").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }),
});

export const oauthClient = pgTable(
    "oauth_client",
    {
        id: text("id").primaryKey(),
        clientId: text("client_id").notNull().unique(),
        clientSecret: text("client_secret"),
        // Required for CIMD ownership and refresh. Discovery-owned clients
        // must not be mutable through managed-client paths.
        clientDiscoveryId: text("client_discovery_id"),
        disabled: boolean("disabled").default(false),
        skipConsent: boolean("skip_consent"),
        enableEndSession: boolean("enable_end_session"),
        subjectType: text("subject_type"),
        scopes: text("scopes").array(),
        clientCredentialsScopes: text("client_credentials_scopes")
            .array()
            .notNull()
            .default([]),
        userId: text("user_id").references(() => user.id, {
            onDelete: "cascade",
        }),
        createdAt: timestamp("created_at", { withTimezone: true }),
        updatedAt: timestamp("updated_at", { withTimezone: true }),
        name: text("name"),
        uri: text("uri"),
        icon: text("icon"),
        contacts: text("contacts").array(),
        tos: text("tos"),
        policy: text("policy"),
        softwareId: text("software_id"),
        softwareVersion: text("software_version"),
        softwareStatement: text("software_statement"),
        redirectUris: text("redirect_uris").array().notNull(),
        postLogoutRedirectUris: text("post_logout_redirect_uris").array(),
        backchannelLogoutUri: text("backchannel_logout_uri"),
        backchannelLogoutSessionRequired: boolean(
            "backchannel_logout_session_required",
        ),
        tokenEndpointAuthMethod: text("token_endpoint_auth_method"),
        applicationType: text("application_type"),
        jwks: text("jwks"),
        jwksUri: text("jwks_uri"),
        grantTypes: text("grant_types").array(),
        responseTypes: text("response_types").array(),
        public: boolean("public"),
        type: text("type"),
        requirePKCE: boolean("require_pkce"),
        dpopBoundAccessTokens: boolean("dpop_bound_access_tokens").default(
            false,
        ),
        referenceId: text("reference_id"),
        metadata: jsonb("metadata"),
    },
    (table) => ({
        userIdIdx: index("auth_oauth_client_user_id_idx").on(table.userId),
    }),
);

/** Better Auth OAuth Provider's persistent protected-resource registry.
 * CIMD authorization uses this to bind the MCP resource indicator to its
 * allowed scopes and token policy. */
export const oauthResource = pgTable("oauth_resource", {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull().unique(),
    name: text("name").notNull(),
    accessTokenTtl: integer("access_token_ttl"),
    refreshTokenTtl: integer("refresh_token_ttl"),
    signingAlgorithm: text("signing_algorithm"),
    signingKeyId: text("signing_key_id"),
    allowedScopes: text("allowed_scopes").array(),
    customClaims: jsonb("custom_claims"),
    dpopBoundAccessTokensRequired: boolean("dpop_bound_access_tokens_required")
        .notNull()
        .default(false),
    disabled: boolean("disabled").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }),
    updatedAt: timestamp("updated_at", { withTimezone: true }),
    policyVersion: integer("policy_version").notNull().default(1),
    metadata: jsonb("metadata"),
});

/** Optional per-client resource linkage used by Better Auth's OAuth provider.
 * The provider keeps this table even when resource enforcement is currently
 * permissive, so future policy tightening needs no schema rewrite. */
export const oauthClientResource = pgTable(
    "oauth_client_resource",
    {
        id: text("id").primaryKey(),
        clientId: text("client_id")
            .notNull()
            .references(() => oauthClient.clientId, { onDelete: "cascade" }),
        resourceId: text("resource_id")
            .notNull()
            .references(() => oauthResource.identifier, {
                onDelete: "cascade",
            }),
        metadata: jsonb("metadata"),
        createdAt: timestamp("created_at", { withTimezone: true }),
    },
    (table) => ({
        clientIdIdx: index("auth_oauth_client_resource_client_id_idx").on(
            table.clientId,
        ),
        resourceIdIdx: index("auth_oauth_client_resource_resource_id_idx").on(
            table.resourceId,
        ),
        clientResourceUnique: uniqueIndex(
            "auth_oauth_client_resource_client_id_resource_id_idx",
        ).on(table.clientId, table.resourceId),
    }),
);

export const oauthRefreshToken = pgTable(
    "oauth_refresh_token",
    {
        id: text("id").primaryKey(),
        token: text("token").notNull().unique(),
        clientId: text("client_id")
            .notNull()
            .references(() => oauthClient.clientId, {
                onDelete: "cascade",
            }),
        sessionId: text("session_id").references(() => session.id, {
            onDelete: "set null",
        }),
        userId: text("user_id")
            .notNull()
            .references(() => user.id, { onDelete: "cascade" }),
        referenceId: text("reference_id"),
        authorizationCodeId: text("authorization_code_id"),
        resources: text("resources").array(),
        requestedUserInfoClaims: text("requested_user_info_claims").array(),
        expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
        createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
        revoked: timestamp("revoked", { withTimezone: true }),
        rotatedAt: timestamp("rotated_at", { withTimezone: true }),
        rotationReplayResponse: text("rotation_replay_response"),
        rotationReplayExpiresAt: timestamp("rotation_replay_expires_at", {
            withTimezone: true,
        }),
        authTime: timestamp("auth_time", { withTimezone: true }),
        confirmation: jsonb("confirmation"),
        scopes: text("scopes").array().notNull(),
    },
    (table) => ({
        clientIdIdx: index("auth_oauth_refresh_token_client_id_idx").on(
            table.clientId,
        ),
        authorizationCodeIdIdx: index(
            "auth_oauth_refresh_token_authorization_code_id_idx",
        ).on(table.authorizationCodeId),
        sessionIdIdx: index("auth_oauth_refresh_token_session_id_idx").on(
            table.sessionId,
        ),
        userIdIdx: index("auth_oauth_refresh_token_user_id_idx").on(
            table.userId,
        ),
    }),
);

export const oauthAccessToken = pgTable(
    "oauth_access_token",
    {
        id: text("id").primaryKey(),
        token: text("token").notNull().unique(),
        clientId: text("client_id")
            .notNull()
            .references(() => oauthClient.clientId, {
                onDelete: "cascade",
            }),
        sessionId: text("session_id").references(() => session.id, {
            onDelete: "set null",
        }),
        userId: text("user_id").references(() => user.id, {
            onDelete: "cascade",
        }),
        referenceId: text("reference_id"),
        authorizationCodeId: text("authorization_code_id"),
        resources: text("resources").array(),
        requestedUserInfoClaims: text("requested_user_info_claims").array(),
        refreshId: text("refresh_id").references(() => oauthRefreshToken.id, {
            onDelete: "set null",
        }),
        expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
        createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
        scopes: text("scopes").array().notNull(),
        confirmation: jsonb("confirmation"),
    },
    (table) => ({
        clientIdIdx: index("auth_oauth_access_token_client_id_idx").on(
            table.clientId,
        ),
        sessionIdIdx: index("auth_oauth_access_token_session_id_idx").on(
            table.sessionId,
        ),
        userIdIdx: index("auth_oauth_access_token_user_id_idx").on(
            table.userId,
        ),
        authorizationCodeIdIdx: index(
            "auth_oauth_access_token_authorization_code_id_idx",
        ).on(table.authorizationCodeId),
        refreshIdIdx: index("auth_oauth_access_token_refresh_id_idx").on(
            table.refreshId,
        ),
    }),
);

export const oauthConsent = pgTable(
    "oauth_consent",
    {
        id: text("id").primaryKey(),
        clientId: text("client_id")
            .notNull()
            .references(() => oauthClient.clientId, {
                onDelete: "cascade",
            }),
        userId: text("user_id").references(() => user.id, {
            onDelete: "cascade",
        }),
        referenceId: text("reference_id"),
        resources: text("resources").array(),
        requestedUserInfoClaims: text("requested_user_info_claims").array(),
        scopes: text("scopes").array().notNull(),
        createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
    },
    (table) => ({
        clientIdIdx: index("auth_oauth_consent_client_id_idx").on(
            table.clientId,
        ),
        userIdIdx: index("auth_oauth_consent_user_id_idx").on(table.userId),
    }),
);

/** Single-use identifiers for private_key_jwt client assertions. The local
 * MCP client is public and does not use these, but keeping the provider's
 * complete schema makes the configured plugin safe to extend. */
export const oauthClientAssertion = pgTable("oauth_client_assertion", {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
});

/** The team an OAuth end-user picked on the post-login "select a team" screen
 * (`/oauth/select-team`, shown only when their account belongs to more than
 * one team — mirrors Notion's workspace picker). One row per Better Auth
 * session, written when the user submits their choice and read back by
 * `oauthProvider`'s `postLogin.consentReferenceId` hook (see
 * `auth/better-auth.ts`), which threads it through as the OAuth `referenceId`
 * so it ends up on the minted access token's `team_id` claim
 * (`customAccessTokenClaims`). Without this, a generic OAuth/MCP client has no
 * way to tell SendLit which team to scope its requests to — there is no
 * standard OAuth mechanism for it, and the custom `X-Sendlit-Team-Id` header
 * only works for clients SendLit itself controls (the web dashboard). */
export const oauthPostLoginTeamSelections = pgTable(
    "oauth_post_login_team_selections",
    {
        sessionId: text("session_id")
            .primaryKey()
            .references(() => session.id, { onDelete: "cascade" }),
        teamId: uuid("team_id")
            .notNull()
            .references(() => teams.id, { onDelete: "cascade" }),
        updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    },
);

/** Organization keys provision/manage resources only inside one organization. */
export const organizationApiKeys = pgTable(
    "organization_api_keys",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        organizationApiKeyId: text("organization_api_key_id")
            .notNull()
            .unique()
            .$defaultFn(() => genPublicId("oak")),
        organizationId: uuid("organization_id")
            .notNull()
            .references(() => organizations.id, { onDelete: "cascade" }),
        name: text("name").notNull(),
        keyHash: text("key_hash").notNull().unique(),
        keyPrefix: text("key_prefix").notNull(),
        scopes: text("scopes").array().notNull().default([]),
        expiresAt: timestamp("expires_at", { withTimezone: true }),
        lastUsedAt: timestamp("last_used_at", { withTimezone: true }),
        revokedAt: timestamp("revoked_at", { withTimezone: true }),
        createdByUserId: text("created_by_user_id").references(() => user.id, {
            onDelete: "set null",
        }),
        createdAt: timestamp("created_at", { withTimezone: true })
            .notNull()
            .defaultNow(),
    },
    (table) => ({
        organizationApiKeyIdCheck: publicIdCheck(
            "organization_api_keys_public_id_check",
            table.organizationApiKeyId,
            "oak",
        ),
        organizationIdx: index("organization_api_keys_organization_id_idx").on(
            table.organizationId,
        ),
    }),
);

/** A team key authenticates as exactly one team and never as a user/org. */
export const teamApiKeys = pgTable(
    "team_api_keys",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        teamApiKeyId: text("team_api_key_id")
            .notNull()
            .unique()
            .$defaultFn(() => genPublicId("tak")),
        teamId: uuid("team_id")
            .notNull()
            .references(() => teams.id, { onDelete: "cascade" }),
        keyHash: text("key_hash").notNull().unique(),
        keyPrefix: text("key_prefix").notNull(),
        name: text("name").notNull(),
        expiresAt: timestamp("expires_at", { withTimezone: true }),
        lastUsedAt: timestamp("last_used_at", { withTimezone: true }),
        revokedAt: timestamp("revoked_at", { withTimezone: true }),
        createdByType: text("created_by_type").notNull().default("user"),
        createdById: text("created_by_id"),
        createdAt: timestamp("created_at", { withTimezone: true })
            .notNull()
            .defaultNow(),
    },
    (table) => ({
        teamApiKeyIdCheck: publicIdCheck(
            "team_api_keys_public_id_check",
            table.teamApiKeyId,
            "tak",
        ),
        teamIdx: index("team_api_keys_team_id_idx").on(table.teamId),
        createdByTypeCheck: check(
            "team_api_keys_created_by_type_check",
            sql`${table.createdByType} IN ('user', 'organization_key', 'system')`,
        ),
    }),
);

/** A contact is a recipient/subscriber. Equivalent of CourseLit's `User` model,
 * stripped of everything course/product related. `contactId` is the public
 * handle (`cnt_...`); `id` is internal-only. */
export const contacts = pgTable(
    "contacts",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        teamId: uuid("team_id")
            .notNull()
            .references(() => teams.id, { onDelete: "cascade" }),
        contactId: text("contact_id")
            .notNull()
            .unique()
            .$defaultFn(() => genPublicId("cnt")),
        email: text("email").notNull(),
        name: text("name"),
        subscribed: boolean("subscribed").notNull().default(true),
        // Intentionally kept alongside `contact_custom_field_values`: this
        // jsonb is the denormalized public read/render snapshot (API
        // responses, merge tags), while the table is the indexed store used
        // for segmentation queries.
        customFields: jsonb("custom_fields")
            .$type<CustomFields>()
            .notNull()
            .default({}),
        tags: text("tags").array().notNull().default([]),
        unsubscribeToken: text("unsubscribe_token").notNull().unique(),
        createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    },
    (table) => ({
        teamEmailIdx: uniqueIndex("contacts_team_id_email_idx").on(
            table.teamId,
            table.email,
        ),
        contactIdCheck: publicIdCheck(
            "contacts_contact_id_check",
            table.contactId,
            "cnt",
        ),
    }),
);

/** Indexed custom field values for scalable generic contact segmentation.
 * `contacts.customFields` remains the public/read snapshot; this table stores
 * one row per scalar value, including each element of scalar arrays.
 * `contactId` here references the contact's *internal* id. */
export const contactCustomFieldValues = pgTable(
    "contact_custom_field_values",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        teamId: uuid("team_id")
            .notNull()
            .references(() => teams.id, { onDelete: "cascade" }),
        contactId: uuid("contact_id")
            .notNull()
            .references(() => contacts.id, { onDelete: "cascade" }),
        key: text("key").notNull(),
        valueType: text("value_type").notNull(), // string | number | boolean | date
        valueText: text("value_text"),
        valueNumber: doublePrecision("value_number"),
        valueBoolean: boolean("value_boolean"),
        valueDate: timestamp("value_date", { withTimezone: true }),
        createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    },
    (table) => ({
        contactKeyIdx: index("contact_custom_field_values_contact_key_idx").on(
            table.teamId,
            table.contactId,
            table.key,
        ),
        textLookupIdx: index("contact_custom_field_values_text_lookup_idx").on(
            table.teamId,
            table.key,
            table.valueText,
        ),
        numberLookupIdx: index(
            "contact_custom_field_values_number_lookup_idx",
        ).on(table.teamId, table.key, table.valueNumber),
        booleanLookupIdx: index(
            "contact_custom_field_values_boolean_lookup_idx",
        ).on(table.teamId, table.key, table.valueBoolean),
        dateLookupIdx: index("contact_custom_field_values_date_lookup_idx").on(
            table.teamId,
            table.key,
            table.valueDate,
        ),
    }),
);

export const emailTemplates = pgTable(
    "email_templates",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        teamId: uuid("team_id")
            .notNull()
            .references(() => teams.id, { onDelete: "cascade" }),
        templateId: text("template_id")
            .notNull()
            .unique()
            .$defaultFn(() => genPublicId("tpl")),
        title: text("title").notNull(),
        purpose: text("purpose", {
            enum: ["marketing", "transactional"],
        })
            .notNull()
            .default("marketing"),
        // { content: EmailBlock[], style: EmailStyle, meta: EmailMeta } — see @sendlit/email-editor
        content: jsonb("content").notNull(),
        createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    },
    (table) => ({
        teamTitleIdx: uniqueIndex("email_templates_team_id_title_idx").on(
            table.teamId,
            table.title,
        ),
        templateIdCheck: publicIdCheck(
            "email_templates_template_id_check",
            table.templateId,
            "tpl",
        ),
        purposeCheck: check(
            "email_templates_purpose_check",
            sql`${table.purpose} in ('marketing', 'transactional')`,
        ),
    }),
);

export const media = pgTable(
    "media",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        teamId: uuid("team_id")
            .notNull()
            .references(() => teams.id, { onDelete: "cascade" }),
        mediaId: text("media_id")
            .notNull()
            .unique()
            .$defaultFn(() => genPublicId("med")),
        mediaLitId: text("media_lit_id").notNull(),
        url: text("url").notNull(),
        thumbnailUrl: text("thumbnail_url"),
        fileName: text("file_name"),
        mimeType: text("mime_type"),
        size: integer("size"),
        width: integer("width"),
        height: integer("height"),
        alt: text("alt"),
        caption: text("caption"),
        createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    },
    (table) => ({
        mediaIdCheck: publicIdCheck(
            "media_media_id_check",
            table.mediaId,
            "med",
        ),
        teamMediaLitIdx: uniqueIndex("media_team_id_media_lit_id_idx").on(
            table.teamId,
            table.mediaLitId,
        ),
        teamCreatedAtIdx: index("media_team_id_created_at_idx").on(
            table.teamId,
            table.createdAt,
        ),
    }),
);

export const mediaReferences = pgTable(
    "media_references",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        teamId: uuid("team_id")
            .notNull()
            .references(() => teams.id, { onDelete: "cascade" }),
        mediaId: uuid("media_id")
            .notNull()
            .references(() => media.id, { onDelete: "cascade" }),
        resourceType: text("resource_type").notNull(),
        resourceInternalId: uuid("resource_internal_id").notNull(),
        resourcePublicId: text("resource_public_id").notNull(),
        parentResourceInternalId: uuid("parent_resource_internal_id"),
        parentResourcePublicId: text("parent_resource_public_id"),
        createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    },
    (table) => ({
        resourceIdx: index("media_references_resource_idx").on(
            table.teamId,
            table.resourceType,
            table.resourceInternalId,
        ),
        mediaIdx: index("media_references_media_id_idx").on(table.mediaId),
        uniqueResourceMediaIdx: uniqueIndex(
            "media_references_resource_media_idx",
        ).on(
            table.teamId,
            table.resourceType,
            table.resourceInternalId,
            table.mediaId,
        ),
    }),
);

/** A saved, named, reusable contact filter — the persisted form of the
 * `ContactFilterWithAggregator` shape (see `contacts/segment.ts`) that
 * `sequences.filter`/`excludeFilter` already store inline per-broadcast. This
 * table lets a team build a filter once and reuse it by name instead of
 * re-building it for every broadcast/sequence. */
export const segments = pgTable(
    "segments",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        teamId: uuid("team_id")
            .notNull()
            .references(() => teams.id, { onDelete: "cascade" }),
        segmentId: text("segment_id")
            .notNull()
            .unique()
            .$defaultFn(() => genPublicId("seg")),
        name: text("name").notNull(),
        // ContactFilterWithAggregator — see contacts/segment.ts
        filter: jsonb("filter").notNull(),
        createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    },
    (table) => ({
        teamNameIdx: uniqueIndex("segments_team_id_name_idx").on(
            table.teamId,
            table.name,
        ),
        segmentIdCheck: publicIdCheck(
            "segments_segment_id_check",
            table.segmentId,
            "seg",
        ),
    }),
);

/** One immutable ownership model for organization- and team-owned ESPs. */
export const espConfigs = pgTable(
    "esp_configs",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        espId: text("esp_id")
            .notNull()
            .unique()
            .$defaultFn(() => genPublicId("esp")),
        ownerScope: text("owner_scope").notNull(),
        organizationId: uuid("organization_id").references(
            () => organizations.id,
            { onDelete: "restrict" },
        ),
        teamId: uuid("team_id").references(() => teams.id, {
            onDelete: "restrict",
        }),
        name: text("name").notNull(),
        provider: text("provider").notNull().default("smtp"),
        host: text("host").notNull(),
        port: integer("port").notNull().default(587),
        secure: boolean("secure").notNull().default(false),
        username: text("username"),
        encryptedSecret: text("encrypted_secret"),
        fromName: text("from_name"),
        fromEmail: text("from_email"),
        status: text("status").notNull().default("draft"),
        secretVersion: integer("secret_version").notNull().default(1),
        lastTestedAt: timestamp("last_tested_at", { withTimezone: true }),
        lastTestStatus: text("last_test_status"), // success | failed
        lastTestError: text("last_test_error"),
        activatedAt: timestamp("activated_at", { withTimezone: true }),
        drainUntil: timestamp("drain_until", { withTimezone: true }),
        retiredAt: timestamp("retired_at", { withTimezone: true }),
        createdAt: timestamp("created_at", { withTimezone: true })
            .notNull()
            .defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true })
            .notNull()
            .defaultNow(),
    },
    (table) => ({
        espIdCheck: publicIdCheck(
            "esp_configs_esp_id_check",
            table.espId,
            "esp",
        ),
        organizationIdx: index("esp_configs_organization_id_idx").on(
            table.organizationId,
        ),
        teamIdx: index("esp_configs_team_id_idx").on(table.teamId),
        idOrganizationIdx: unique("esp_configs_id_organization_id_unique").on(
            table.id,
            table.organizationId,
        ),
        idTeamIdx: unique("esp_configs_id_team_id_unique").on(
            table.id,
            table.teamId,
        ),
        ownerCheck: check(
            "esp_configs_owner_check",
            sql`(${table.ownerScope} = 'organization' AND ${table.organizationId} IS NOT NULL AND ${table.teamId} IS NULL)
                OR (${table.ownerScope} = 'team' AND ${table.organizationId} IS NULL AND ${table.teamId} IS NOT NULL)`,
        ),
        statusCheck: check(
            "esp_configs_status_check",
            sql`${table.status} IN ('draft', 'active', 'suspended', 'draining', 'retired')`,
        ),
    }),
);

export const organizationDeliveryPolicies = pgTable(
    "organization_delivery_policies",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        organizationId: uuid("organization_id")
            .notNull()
            .unique()
            .references(() => organizations.id, { onDelete: "cascade" }),
        defaultEspConfigId: uuid("default_esp_config_id"),
        autoGrantDefaultEsp: boolean("auto_grant_default_esp")
            .notNull()
            .default(false),
        defaultDailyLimit: integer("default_daily_limit"),
        defaultMonthlyLimit: integer("default_monthly_limit"),
        aggregateDailyLimit: integer("aggregate_daily_limit"),
        aggregateMonthlyLimit: integer("aggregate_monthly_limit"),
        teamEspEnabledByDefault: boolean("team_esp_enabled_by_default")
            .notNull()
            .default(true),
        teamCanChangeDefault: boolean("team_can_change_default")
            .notNull()
            .default(true),
        createdAt: timestamp("created_at", { withTimezone: true })
            .notNull()
            .defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true })
            .notNull()
            .defaultNow(),
    },
    (table) => ({
        defaultEspFk: foreignKey({
            name: "organization_delivery_policies_default_esp_fk",
            columns: [table.defaultEspConfigId, table.organizationId],
            foreignColumns: [espConfigs.id, espConfigs.organizationId],
        }).onDelete("restrict"),
        limitCheck: check(
            "organization_delivery_policies_limit_check",
            sql`(${table.defaultDailyLimit} IS NULL OR ${table.defaultDailyLimit} >= 0)
                AND (${table.defaultMonthlyLimit} IS NULL OR ${table.defaultMonthlyLimit} >= 0)
                AND (${table.aggregateDailyLimit} IS NULL OR ${table.aggregateDailyLimit} >= 0)
                AND (${table.aggregateMonthlyLimit} IS NULL OR ${table.aggregateMonthlyLimit} >= 0)`,
        ),
    }),
);

export const espConfigTeamGrants = pgTable(
    "esp_config_team_grants",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        grantId: text("grant_id")
            .notNull()
            .unique()
            .$defaultFn(() => genPublicId("egr")),
        organizationId: uuid("organization_id").notNull(),
        espConfigId: uuid("esp_config_id").notNull(),
        teamId: uuid("team_id").notNull(),
        status: text("status").notNull().default("active"),
        drainUntil: timestamp("drain_until", { withTimezone: true }),
        fromName: text("from_name"),
        replyTo: text("reply_to"),
        dailyLimit: integer("daily_limit"),
        monthlyLimit: integer("monthly_limit"),
        createdByType: text("created_by_type").notNull(),
        createdById: text("created_by_id"),
        createdAt: timestamp("created_at", { withTimezone: true })
            .notNull()
            .defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true })
            .notNull()
            .defaultNow(),
    },
    (table) => ({
        grantIdCheck: publicIdCheck(
            "esp_config_team_grants_public_id_check",
            table.grantId,
            "egr",
        ),
        activeTeamIdx: uniqueIndex(
            "esp_config_team_grants_non_revoked_team_idx",
        )
            .on(table.teamId)
            .where(sql`${table.status} <> 'revoked'`),
        idOrganizationUnique: unique(
            "esp_config_team_grants_id_organization_id_unique",
        ).on(table.id, table.organizationId),
        pinUnique: unique("esp_config_team_grants_id_team_esp_unique").on(
            table.id,
            table.teamId,
            table.espConfigId,
        ),
        teamOrganizationFk: foreignKey({
            name: "esp_config_team_grants_team_organization_fk",
            columns: [table.teamId, table.organizationId],
            foreignColumns: [teams.id, teams.organizationId],
        }).onDelete("restrict"),
        espOrganizationFk: foreignKey({
            name: "esp_config_team_grants_esp_organization_fk",
            columns: [table.espConfigId, table.organizationId],
            foreignColumns: [espConfigs.id, espConfigs.organizationId],
        }).onDelete("restrict"),
        statusCheck: check(
            "esp_config_team_grants_status_check",
            sql`${table.status} IN ('active', 'draining', 'suspended', 'revoked')`,
        ),
        limitCheck: check(
            "esp_config_team_grants_limit_check",
            sql`(${table.dailyLimit} IS NULL OR ${table.dailyLimit} >= 0)
                AND (${table.monthlyLimit} IS NULL OR ${table.monthlyLimit} >= 0)`,
        ),
        createdByTypeCheck: check(
            "esp_config_team_grants_created_by_type_check",
            sql`${table.createdByType} IN ('user', 'organization_key', 'system')`,
        ),
    }),
);

export const teamDeliverySettings = pgTable(
    "team_delivery_settings",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        teamId: uuid("team_id")
            .notNull()
            .unique()
            .references(() => teams.id, { onDelete: "cascade" }),
        teamEspEnabled: boolean("team_esp_enabled").notNull().default(true),
        teamCanChangeDefault: boolean("team_can_change_default")
            .notNull()
            .default(true),
        defaultSource: text("default_source"),
        defaultTeamEspConfigId: uuid("default_team_esp_config_id"),
        createdAt: timestamp("created_at", { withTimezone: true })
            .notNull()
            .defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true })
            .notNull()
            .defaultNow(),
    },
    (table) => ({
        defaultTeamEspFk: foreignKey({
            name: "team_delivery_settings_default_team_esp_fk",
            columns: [table.defaultTeamEspConfigId, table.teamId],
            foreignColumns: [espConfigs.id, espConfigs.teamId],
        }).onDelete("restrict"),
        defaultSourceCheck: check(
            "team_delivery_settings_default_source_check",
            sql`${table.defaultSource} IS NULL OR ${table.defaultSource} IN ('organization', 'team')`,
        ),
    }),
);

/** Per-team general workspace settings ("settings.general") — a per-team
 * singleton like `esp_configs`, addressed via the team (`/settings/general`),
 * so no public `<domain>_id` is needed. `mailingAddress` is the physical
 * postal address rendered in email footers (CAN-SPAM/GDPR requirement). */
export const settings = pgTable("settings", {
    id: uuid("id").$defaultFn(genId).primaryKey(),
    teamId: uuid("team_id")
        .notNull()
        .unique()
        .references(() => teams.id, { onDelete: "cascade" }),
    mailingAddress: text("mailing_address"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

/** A broadcast (one-off, `type = 'broadcast'`) or a sequence (multi-step,
 * `type = 'sequence'`) — same shape as CourseLit's `Sequence` model. */
export const sequences = pgTable(
    "sequences",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        teamId: uuid("team_id")
            .notNull()
            .references(() => teams.id, { onDelete: "cascade" }),
        sequenceId: text("sequence_id")
            .notNull()
            .unique()
            .$defaultFn(() => genPublicId("seq")),
        type: text("type").notNull(), // 'broadcast' | 'sequence'
        title: text("title").notNull().default(""),
        status: text("status").notNull().default("draft"), // draft|active|paused|completed
        deliverySourceIntent: jsonb("delivery_source_intent"),
        // Resolved and pinned atomically at activation. Drafts may leave these
        // null while retaining their public source intent in the API layer.
        deliverySourceType: text("delivery_source_type"), // organization | team
        outboxId: uuid("outbox_id").references(() => espConfigs.id, {
            onDelete: "restrict",
        }),
        espGrantId: uuid("esp_grant_id").references(
            () => espConfigTeamGrants.id,
            { onDelete: "restrict" },
        ),
        triggerType: text("trigger_type"), // Constants.EventType
        triggerData: text("trigger_data"),
        // UserFilterWithAggregator — see contacts/segment.ts
        filter: jsonb("filter"),
        excludeFilter: jsonb("exclude_filter"),
        emailsOrder: text("emails_order").array().notNull().default([]),
        entrants: text("entrants").array().notNull().default([]),
        // { broadcast: { sentAt, lockedAt }, sequence: { subscribers, unsubscribers, failed } }
        report: jsonb("report").notNull().default({}),
        createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    },
    (table) => ({
        sequenceIdCheck: publicIdCheck(
            "sequences_sequence_id_check",
            table.sequenceId,
            "seq",
        ),
        deliveryPinCheck: check(
            "sequences_delivery_pin_check",
            sql`(
                ${table.deliverySourceType} IS NULL
                AND ${table.outboxId} IS NULL
                AND ${table.espGrantId} IS NULL
            ) OR (
                ${table.deliverySourceType} = 'team'
                AND ${table.outboxId} IS NOT NULL
                AND ${table.espGrantId} IS NULL
            ) OR (
                ${table.deliverySourceType} = 'organization'
                AND ${table.outboxId} IS NOT NULL
                AND ${table.espGrantId} IS NOT NULL
            )`,
        ),
    }),
);

/** A structural child of exactly one `sequences` row — never addressed
 * independently, so `sequenceId` references the parent's internal `id`
 * (unlike the event/log tables below, which store the public id). `emailId`
 * is this row's own public handle within that sequence. */
export const sequenceEmails = pgTable(
    "sequence_emails",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        sequenceId: uuid("sequence_id")
            .notNull()
            .references(() => sequences.id, { onDelete: "cascade" }),
        emailId: text("email_id")
            .notNull()
            .$defaultFn(() => genPublicId("email")),
        subject: text("subject").notNull(),
        // { content: EmailBlock[], style: EmailStyle, meta: EmailMeta }
        content: jsonb("content").notNull(),
        delayInMillis: bigint("delay_in_millis", { mode: "number" })
            .notNull()
            .default(86400000),
        published: boolean("published").notNull().default(false),
        templateId: text("template_id"),
        actionType: text("action_type"), // tag:add | tag:remove
        actionData: jsonb("action_data"),
        createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    },
    (table) => ({
        sequenceEmailIdx: uniqueIndex(
            "sequence_emails_sequence_id_email_id_idx",
        ).on(table.sequenceId, table.emailId),
        emailIdCheck: publicIdCheck(
            "sequence_emails_email_id_check",
            table.emailId,
            "email",
        ),
    }),
);

/** A scheduled trigger for a sequence — e.g. "fire DATE_OCCURRED for broadcast X at
 * time T", processed by `automation/process-rules.ts`. Not exposed via any
 * REST/MCP route today. */
export const rules = pgTable(
    "rules",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        teamId: uuid("team_id")
            .notNull()
            .references(() => teams.id, { onDelete: "cascade" }),
        ruleId: text("rule_id")
            .notNull()
            .unique()
            .$defaultFn(() => genPublicId("rule")),
        event: text("event").notNull(), // Constants.EventType
        sequenceId: uuid("sequence_id")
            .notNull()
            .references(() => sequences.id, { onDelete: "cascade" }),
        eventDateInMillis: bigint("event_date_in_millis", { mode: "number" }),
        eventData: text("event_data"),
        createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    },
    (table) => ({
        ruleIdCheck: publicIdCheck("rules_rule_id_check", table.ruleId, "rule"),
    }),
);

/** One row per (sequence, contact) currently being delivered. Processed by
 * `automation/process-ongoing-sequence.ts`. */
export const ongoingSequences = pgTable(
    "ongoing_sequences",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        teamId: uuid("team_id")
            .notNull()
            .references(() => teams.id, { onDelete: "cascade" }),
        sequenceId: uuid("sequence_id")
            .notNull()
            .references(() => sequences.id, { onDelete: "cascade" }),
        contactId: uuid("contact_id")
            .notNull()
            .references(() => contacts.id, { onDelete: "cascade" }),
        nextEmailScheduledTime: bigint("next_email_scheduled_time", {
            mode: "number",
        }).notNull(),
        retryCount: integer("retry_count").notNull().default(0),
        sentEmailIds: text("sent_email_ids").array().notNull().default([]),
        processingStartedAt: timestamp("processing_started_at", {
            withTimezone: true,
        }),
        createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    },
    (table) => ({
        sequenceContactIdx: uniqueIndex(
            "ongoing_sequences_sequence_id_contact_id_idx",
        ).on(table.sequenceId, table.contactId),
        // The 60s due-poll (`getDueOngoingSequences`) filters on this column.
        nextScheduledIdx: index(
            "ongoing_sequences_next_email_scheduled_time_idx",
        ).on(table.nextEmailScheduledTime),
    }),
);

export const emailDeliveries = pgTable("email_deliveries", {
    id: uuid("id").$defaultFn(genId).primaryKey(),
    teamId: uuid("team_id")
        .notNull()
        .references(() => teams.id, { onDelete: "cascade" }),
    sequenceId: uuid("sequence_id")
        .notNull()
        .references(() => sequences.id, { onDelete: "cascade" }),
    contactId: uuid("contact_id")
        .notNull()
        .references(() => contacts.id, { onDelete: "cascade" }),
    emailId: uuid("email_id")
        .notNull()
        .references(() => sequenceEmails.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export const emailEvents = pgTable("email_events", {
    id: uuid("id").$defaultFn(genId).primaryKey(),
    teamId: uuid("team_id")
        .notNull()
        .references(() => teams.id, { onDelete: "cascade" }),
    sequenceId: uuid("sequence_id")
        .notNull()
        .references(() => sequences.id, { onDelete: "cascade" }),
    contactId: uuid("contact_id")
        .notNull()
        .references(() => contacts.id, { onDelete: "cascade" }),
    emailId: uuid("email_id")
        .notNull()
        .references(() => sequenceEmails.id, { onDelete: "cascade" }),
    action: text("action").notNull(), // open | click | bounce
    link: text("link"),
    linkIndex: integer("link_index"),
    bounceType: text("bounce_type"), // hard | soft
    bounceReason: text("bounce_reason"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

/** A single API-triggered send — the transactional counterpart of
 * `sequences`/`sequence_emails`, deliberately not modeled as either (see
 * `docs/transactional-emails.md`): recipients are never required to be
 * subscribed `contacts`, no unsubscribe/footer is injected, and delivery is
 * immediate rather than audience-fanned-out. One row per message; the
 * rendered `html` is snapshotted at send time so the log survives later
 * template edits/deletes. `toEmail`/`fromEmail` are suffixed `_email` because
 * `to`/`from` are reserved words in SQL. */
export const transactionalEmails = pgTable(
    "transactional_emails",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        teamId: uuid("team_id")
            .notNull()
            .references(() => teams.id, { onDelete: "cascade" }),
        txeId: text("txe_id")
            .notNull()
            .unique()
            .$defaultFn(() => genPublicId("txe")),
        deliverySourceType: text("delivery_source_type").notNull(),
        outboxId: uuid("outbox_id").references(() => espConfigs.id, {
            onDelete: "restrict",
        }),
        espGrantId: uuid("esp_grant_id").references(
            () => espConfigTeamGrants.id,
            { onDelete: "restrict" },
        ),
        toEmail: text("to_email").notNull(),
        // Resolved sender identity at enqueue time (team ESP fromName/fromEmail
        // fallback chain, same as `attemptMailSending`) — never caller-supplied.
        fromEmail: text("from_email"),
        replyTo: text("reply_to"),
        subject: text("subject").notNull(),
        // Plain text holding the *public* `tpl_` id — same convention as
        // `sequence_emails.templateId` (not a FK): informational only, never
        // resolved for reads, and left dangling if the template is later
        // deleted (harmless — `html`/`subject` are already snapshotted).
        templateId: text("template_id"),
        // Rendered snapshot actually sent (post-Liquid for template sends,
        // verbatim for inline `html` sends) — pre tracking-pixel/click rewrite.
        html: text("html"),
        // Liquid merge payload; only meaningful alongside `templateId` (inline
        // `html` sends are never re-rendered — see PRD's send-pipeline notes).
        variables: jsonb("variables").notNull().default({}),
        headers: jsonb("headers"),
        // Populated opportunistically when `toEmail` matches an existing
        // contact, purely for analytics — never consulted for suppression;
        // `contacts.subscribed` does not apply to transactional mail.
        contactId: uuid("contact_id").references(() => contacts.id, {
            onDelete: "set null",
        }),
        status: text("status").notNull().default("queued"), // queued|sent|failed|bounced|suppressed|cancelled
        processingStartedAt: timestamp("processing_started_at", {
            withTimezone: true,
        }),
        error: text("error"),
        idempotencyKey: text("idempotency_key"),
        trackOpens: boolean("track_opens").notNull().default(false),
        trackClicks: boolean("track_clicks").notNull().default(false),
        openCount: integer("open_count").notNull().default(0),
        clickCount: integer("click_count").notNull().default(0),
        sentAt: timestamp("sent_at", { withTimezone: true }),
        createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    },
    (table) => ({
        txeIdCheck: publicIdCheck(
            "transactional_emails_txe_id_check",
            table.txeId,
            "txe",
        ),
        // Idempotency-key replay lookup — partial, since most sends won't
        // supply one and NULL is never unique-constrained.
        teamIdempotencyKeyIdx: uniqueIndex(
            "transactional_emails_team_id_idempotency_key_idx",
        )
            .on(table.teamId, table.idempotencyKey)
            .where(sql`${table.idempotencyKey} IS NOT NULL`),
        teamCreatedAtIdx: index(
            "transactional_emails_team_id_created_at_idx",
        ).on(table.teamId, table.createdAt),
        teamStatusIdx: index("transactional_emails_team_id_status_idx").on(
            table.teamId,
            table.status,
        ),
        deliveryPinCheck: check(
            "transactional_emails_delivery_pin_check",
            sql`(
                ${table.deliverySourceType} = 'team'
                AND ${table.outboxId} IS NOT NULL
                AND ${table.espGrantId} IS NULL
            ) OR (
                ${table.deliverySourceType} = 'organization'
                AND ${table.outboxId} IS NOT NULL
                AND ${table.espGrantId} IS NOT NULL
            )`,
        ),
    }),
);

/** Provider-specific webhook security/health lifecycle for one feedback
 * connection — deliberately not columns on `esp_configs`, since secrets and
 * health status churn independently of SMTP connection settings (see
 * `docs/bounces-and-complaints.md#2-feedback-connection`). A `custom`
 * connection is pinned to one team-owned `espConfigId`; a future `platform`
 * connection (never created by this phase) has null `teamId`/`espConfigId`
 * and is deployment-managed, never returned through team ESP APIs. */
export const espFeedbackConnections = pgTable(
    "esp_feedback_connections",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        connectionId: text("connection_id")
            .notNull()
            .unique()
            .$defaultFn(() => genPublicId("whc")),
        ownerScope: text("owner_scope").notNull(), // organization | team
        organizationId: uuid("organization_id").references(
            () => organizations.id,
            { onDelete: "restrict" },
        ),
        teamId: uuid("team_id").references(() => teams.id, {
            onDelete: "restrict",
        }),
        espConfigId: uuid("esp_config_id").references(() => espConfigs.id, {
            onDelete: "restrict",
        }),
        provider: text("provider").notNull(),
        encryptedCredentials: text("encrypted_credentials"),
        // Rotation accepts both the current and immediately previous
        // credential for up to 24h so an in-flight provider retry signed
        // with the old secret isn't rejected (PRD's "Feedback connection"
        // rotation requirement). Cleared once expired.
        previousEncryptedCredentials: text("previous_encrypted_credentials"),
        previousCredentialExpiresAt: timestamp(
            "previous_credential_expires_at",
            { withTimezone: true },
        ),
        // SES: the SNS TopicArn this connection expects notifications from.
        expectedTopicArn: text("expected_topic_arn"),
        status: text("status").notNull().default("pending"),
        lastReceivedAt: timestamp("last_received_at", { withTimezone: true }),
        lastVerifiedAt: timestamp("last_verified_at", { withTimezone: true }),
        lastErrorCode: text("last_error_code"),
        disabledAt: timestamp("disabled_at", { withTimezone: true }),
        createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    },
    (table) => ({
        connectionIdCheck: publicIdCheck(
            "esp_feedback_connections_connection_id_check",
            table.connectionId,
            "whc",
        ),
        teamIdx: index("esp_feedback_connections_team_id_idx").on(table.teamId),
        ownerCheck: check(
            "esp_feedback_connections_owner_check",
            sql`(
                ${table.ownerScope} = 'organization'
                AND ${table.organizationId} IS NOT NULL
                AND ${table.teamId} IS NULL
            ) OR (
                ${table.ownerScope} = 'team'
                AND ${table.organizationId} IS NULL
                AND ${table.teamId} IS NOT NULL
            )`,
        ),
        // At most one non-retired connection per user ESP — a provider
        // change retires the old row (status -> retiring) and inserts a new
        // one rather than mutating provider in place.
        espConfigActiveIdx: uniqueIndex(
            "esp_feedback_connections_esp_config_active_idx",
        )
            .on(table.espConfigId)
            .where(
                sql`${table.espConfigId} is not null and ${table.status} not in ('retiring', 'disabled')`,
            ),
    }),
);

/** One row per (recipient) submission across broadcasts, sequences, and
 * transactional sends — the common ledger `docs/bounces-and-complaints.md`
 * requires so a later provider webhook can correlate back to a workspace,
 * source, and pinned ESP regardless of which pipeline sent it. Created
 * before transport and updated with the transport result; the current
 * `deliveryStatus`/`feedbackStatus` are a projection maintained by
 * `feedback/projection.ts`, kept separate from the immutable
 * `emailDeliveryEvents` log so retries/out-of-order events can't corrupt it. */
export const outboundMessages = pgTable(
    "outbound_messages",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        messageId: text("message_id")
            .notNull()
            .unique()
            .$defaultFn(() => genPublicId("msg")),
        teamId: uuid("team_id")
            .notNull()
            .references(() => teams.id, { onDelete: "cascade" }),
        deliverySourceType: text("delivery_source_type").notNull(),
        espConfigId: uuid("esp_config_id").references(() => espConfigs.id, {
            onDelete: "restrict",
        }),
        espGrantId: uuid("esp_grant_id").references(
            () => espConfigTeamGrants.id,
            { onDelete: "restrict" },
        ),
        feedbackConnectionId: uuid("feedback_connection_id").references(
            () => espFeedbackConnections.id,
            { onDelete: "set null" },
        ),
        sourceType: text("source_type").notNull(), // campaign | transactional
        // Stable application-level submission identity. Retries reuse the
        // same ledger row and RFC Message-ID rather than creating a second
        // provider-correlatable message.
        submissionKey: text("submission_key").unique(),
        // Exactly one of these two is populated, matching `sourceType`.
        campaignDeliveryId: uuid("campaign_delivery_id").references(
            () => emailDeliveries.id,
            { onDelete: "set null" },
        ),
        transactionalEmailId: uuid("transactional_email_id").references(
            () => transactionalEmails.id,
            { onDelete: "set null" },
        ),
        recipientEmail: text("recipient_email").notNull(),
        normalizedRecipient: text("normalized_recipient").notNull(),
        // Snapshot of the pinned ESP's provider at send time — never
        // resolved from the team's *current* default, so historical
        // correlation survives a later default switch.
        provider: text("provider"),
        rfcMessageId: text("rfc_message_id"),
        providerMessageId: text("provider_message_id"),
        deliveryStatus: text("delivery_status").notNull().default("queued"),
        feedbackStatus: text("feedback_status").notNull().default("none"),
        acceptedAt: timestamp("accepted_at", { withTimezone: true }),
        deliveredAt: timestamp("delivered_at", { withTimezone: true }),
        bouncedAt: timestamp("bounced_at", { withTimezone: true }),
        complainedAt: timestamp("complained_at", { withTimezone: true }),
        lastEventAt: timestamp("last_event_at", { withTimezone: true }),
        createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    },
    (table) => ({
        messageIdCheck: publicIdCheck(
            "outbound_messages_message_id_check",
            table.messageId,
            "msg",
        ),
        teamCreatedAtIdx: index("outbound_messages_team_id_created_at_idx").on(
            table.teamId,
            table.createdAt,
        ),
        connectionProviderMsgIdx: index(
            "outbound_messages_connection_provider_msg_idx",
        ).on(table.feedbackConnectionId, table.providerMessageId),
        recipientHistoryIdx: index(
            "outbound_messages_team_id_recipient_created_at_idx",
        ).on(table.teamId, table.normalizedRecipient, table.createdAt),
        deliveryPinCheck: check(
            "outbound_messages_delivery_pin_check",
            sql`(
                ${table.deliverySourceType} = 'team'
                AND ${table.espConfigId} IS NOT NULL
                AND ${table.espGrantId} IS NULL
            ) OR (
                ${table.deliverySourceType} = 'organization'
                AND ${table.espConfigId} IS NOT NULL
                AND ${table.espGrantId} IS NOT NULL
            )`,
        ),
    }),
);

/** Atomic quota counters for organization-owned delivery. */
export const organizationEspUsageBuckets = pgTable(
    "organization_esp_usage_buckets",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        bucketScope: text("bucket_scope").notNull(), // grant | organization
        organizationId: uuid("organization_id")
            .notNull()
            .references(() => organizations.id, { onDelete: "restrict" }),
        grantId: uuid("grant_id").references(() => espConfigTeamGrants.id, {
            onDelete: "restrict",
        }),
        periodType: text("period_type").notNull(), // day | month
        periodStart: timestamp("period_start", {
            withTimezone: true,
        }).notNull(),
        reservedCount: integer("reserved_count").notNull().default(0),
        acceptedCount: integer("accepted_count").notNull().default(0),
        updatedAt: timestamp("updated_at", { withTimezone: true })
            .notNull()
            .defaultNow(),
    },
    (table) => ({
        scopeCheck: check(
            "organization_esp_usage_buckets_scope_check",
            sql`(
                ${table.bucketScope} = 'grant' AND ${table.grantId} IS NOT NULL
            ) OR (
                ${table.bucketScope} = 'organization' AND ${table.grantId} IS NULL
            )`,
        ),
        periodCheck: check(
            "organization_esp_usage_buckets_period_check",
            sql`${table.periodType} IN ('day', 'month')`,
        ),
        countCheck: check(
            "organization_esp_usage_buckets_count_check",
            sql`${table.reservedCount} >= 0 AND ${table.acceptedCount} >= 0`,
        ),
        grantPeriodIdx: uniqueIndex(
            "organization_esp_usage_buckets_grant_period_idx",
        )
            .on(table.grantId, table.periodType, table.periodStart)
            .where(sql`${table.grantId} IS NOT NULL`),
        organizationPeriodIdx: uniqueIndex(
            "organization_esp_usage_buckets_organization_period_idx",
        )
            .on(table.organizationId, table.periodType, table.periodStart)
            .where(sql`${table.bucketScope} = 'organization'`),
        grantOrganizationFk: foreignKey({
            name: "organization_esp_usage_buckets_grant_organization_fk",
            columns: [table.grantId, table.organizationId],
            foreignColumns: [
                espConfigTeamGrants.id,
                espConfigTeamGrants.organizationId,
            ],
        }).onDelete("restrict"),
    }),
);

export const organizationEspQuotaReservations = pgTable(
    "organization_esp_quota_reservations",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        reservationId: text("reservation_id")
            .notNull()
            .unique()
            .$defaultFn(() => genPublicId("qrs")),
        outboundMessageId: uuid("outbound_message_id")
            .notNull()
            .unique()
            .references(() => outboundMessages.id, { onDelete: "restrict" }),
        grantId: uuid("grant_id")
            .notNull()
            .references(() => espConfigTeamGrants.id, {
                onDelete: "restrict",
            }),
        organizationId: uuid("organization_id")
            .notNull()
            .references(() => organizations.id, { onDelete: "restrict" }),
        dayPeriodStart: timestamp("day_period_start", {
            withTimezone: true,
        }).notNull(),
        monthPeriodStart: timestamp("month_period_start", {
            withTimezone: true,
        }).notNull(),
        state: text("state").notNull().default("reserved"),
        releaseReason: text("release_reason"),
        createdAt: timestamp("created_at", { withTimezone: true })
            .notNull()
            .defaultNow(),
        committedAt: timestamp("committed_at", { withTimezone: true }),
        releasedAt: timestamp("released_at", { withTimezone: true }),
    },
    (table) => ({
        reservationIdCheck: publicIdCheck(
            "organization_esp_quota_reservations_reservation_id_check",
            table.reservationId,
            "qrs",
        ),
        stateCheck: check(
            "organization_esp_quota_reservations_state_check",
            sql`${table.state} IN ('reserved', 'committed', 'released')`,
        ),
        grantOrganizationFk: foreignKey({
            name: "organization_esp_quota_reservations_grant_organization_fk",
            columns: [table.grantId, table.organizationId],
            foreignColumns: [
                espConfigTeamGrants.id,
                espConfigTeamGrants.organizationId,
            ],
        }).onDelete("restrict"),
    }),
);

/** Transactional hand-off between PostgreSQL and BullMQ. */
export const mailDispatchOutbox = pgTable(
    "mail_dispatch_outbox",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        dispatchId: text("dispatch_id")
            .notNull()
            .unique()
            .$defaultFn(() => genPublicId("mdj")),
        outboundMessageId: uuid("outbound_message_id")
            .notNull()
            .unique()
            .references(() => outboundMessages.id, { onDelete: "restrict" }),
        queueName: text("queue_name").notNull(),
        jobName: text("job_name").notNull(),
        state: text("state").notNull().default("pending"),
        availableAt: timestamp("available_at", { withTimezone: true })
            .notNull()
            .defaultNow(),
        leaseExpiresAt: timestamp("lease_expires_at", { withTimezone: true }),
        publishAttempts: integer("publish_attempts").notNull().default(0),
        lastError: text("last_error"),
        publishedAt: timestamp("published_at", { withTimezone: true }),
        createdAt: timestamp("created_at", { withTimezone: true })
            .notNull()
            .defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true })
            .notNull()
            .defaultNow(),
    },
    (table) => ({
        dispatchIdCheck: publicIdCheck(
            "mail_dispatch_outbox_dispatch_id_check",
            table.dispatchId,
            "mdj",
        ),
        stateCheck: check(
            "mail_dispatch_outbox_state_check",
            sql`${table.state} IN ('pending', 'publishing', 'published', 'cancelled')`,
        ),
        dueIdx: index("mail_dispatch_outbox_due_idx").on(
            table.state,
            table.availableAt,
        ),
    }),
);

/** Durable, authenticated inbox for raw provider webhook bodies — a request
 * is inserted here and committed *before* the HTTP response is sent, so an
 * acknowledged provider retry can never be lost even if BullMQ/Redis is
 * briefly unavailable (see `docs/bounces-and-complaints.md#4-durable-receipt-inbox`).
 * `teamId` is only ever populated from a `custom` connection — a platform
 * receipt may bundle multiple workspaces in one payload, so team ownership
 * is assigned later, per normalized event, from a uniquely matched
 * `outboundMessages` row. */
export const espWebhookReceipts = pgTable(
    "esp_webhook_receipts",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        receiptId: text("receipt_id")
            .notNull()
            .unique()
            .$defaultFn(() => genPublicId("whr")),
        connectionId: uuid("connection_id")
            .notNull()
            .references(() => espFeedbackConnections.id, {
                onDelete: "cascade",
            }),
        teamId: uuid("team_id").references(() => teams.id, {
            onDelete: "cascade",
        }),
        provider: text("provider").notNull(),
        providerRequestId: text("provider_request_id"),
        bodySha256: text("body_sha256").notNull(),
        // Encrypted raw payload (AES-256-GCM, same utility as ESP
        // credentials) — required on receipt, set null only once the
        // 30-day raw-retention purge runs (see PRD's privacy/retention).
        encryptedPayload: text("encrypted_payload"),
        // Allowlisted non-secret headers only — never Authorization,
        // Cookie, or signature headers.
        safeHeaders: jsonb("safe_headers").notNull().default({}),
        status: text("status").notNull().default("pending"),
        processingAttempts: integer("processing_attempts").notNull().default(0),
        nextAttemptAt: timestamp("next_attempt_at", { withTimezone: true }),
        lastErrorCode: text("last_error_code"),
        receivedAt: timestamp("received_at", { withTimezone: true })
            .notNull()
            .defaultNow(),
        processedAt: timestamp("processed_at", { withTimezone: true }),
    },
    (table) => ({
        receiptIdCheck: publicIdCheck(
            "esp_webhook_receipts_receipt_id_check",
            table.receiptId,
            "whr",
        ),
        // The pending-receipt poller's recovery query and the worker's
        // claim query both filter on this pair.
        statusNextAttemptIdx: index(
            "esp_webhook_receipts_status_next_attempt_idx",
        ).on(table.status, table.nextAttemptAt),
        connectionRequestIdx: index(
            "esp_webhook_receipts_connection_id_provider_request_id_idx",
        ).on(table.connectionId, table.providerRequestId),
    }),
);

/** One immutable row per canonical provider event, derived from a receipt by
 * a provider adapter — the event log `docs/bounces-and-complaints.md`
 * requires to keep retries/out-of-order delivery from corrupting the
 * `outboundMessages` projection. Never updated after insert. */
export const emailDeliveryEvents = pgTable(
    "email_delivery_events",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        eventId: text("event_id")
            .notNull()
            .unique()
            .$defaultFn(() => genPublicId("evt")),
        receiptId: uuid("receipt_id")
            .notNull()
            .references(() => espWebhookReceipts.id, { onDelete: "cascade" }),
        connectionId: uuid("connection_id")
            .notNull()
            .references(() => espFeedbackConnections.id, {
                onDelete: "cascade",
            }),
        // Null until a platform event is uniquely correlated — see
        // `outboundMessageId` note below and the PRD's correlation section.
        teamId: uuid("team_id").references(() => teams.id, {
            onDelete: "cascade",
        }),
        outboundMessageId: uuid("outbound_message_id").references(
            () => outboundMessages.id,
            { onDelete: "set null" },
        ),
        provider: text("provider").notNull(),
        // Deterministic per-adapter idempotency key (e.g. `sg_event_id`, or
        // a composed key when the provider doesn't guarantee one) — see
        // each adapter's "stable event key" requirement in the PRD.
        providerEventKey: text("provider_event_key").notNull(),
        providerMessageId: text("provider_message_id"),
        recipientEmail: text("recipient_email"),
        normalizedRecipient: text("normalized_recipient"),
        eventType: text("event_type").notNull(),
        bounceClass: text("bounce_class"),
        smtpCode: integer("smtp_code"),
        enhancedStatusCode: text("enhanced_status_code"),
        reason: text("reason"),
        remoteMta: text("remote_mta"),
        occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(),
        receivedAt: timestamp("received_at", { withTimezone: true }).notNull(),
        metadata: jsonb("metadata").notNull().default({}),
    },
    (table) => ({
        eventIdCheck: publicIdCheck(
            "email_delivery_events_event_id_check",
            table.eventId,
            "evt",
        ),
        // Event idempotency: replaying the same provider event twice must
        // insert nothing the second time.
        connectionEventKeyIdx: uniqueIndex(
            "email_delivery_events_connection_id_provider_event_key_idx",
        ).on(table.connectionId, table.providerEventKey),
        teamOccurredAtIdx: index(
            "email_delivery_events_team_id_occurred_at_idx",
        ).on(table.teamId, table.occurredAt),
        outboundMessageIdx: index(
            "email_delivery_events_outbound_message_id_idx",
        ).on(table.outboundMessageId),
    }),
);

/** Per-workspace do-not-send list — deliberately not derived from
 * `contacts.subscribed` or the latest message status, so it survives
 * contact deletion/reimport and stays route-independent (any pinned custom
 * ESP, and eventually the platform route, must all respect it). One row per
 * `(teamId, recipientHash)`; repeated signals update `lastSuppressedAt` and
 * keep the strongest `reason` (see `suppressionReasonStrength`). */
export const emailSuppressions = pgTable(
    "email_suppressions",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        suppressionId: text("suppression_id")
            .notNull()
            .unique()
            .$defaultFn(() => genPublicId("sup")),
        teamId: uuid("team_id")
            .notNull()
            .references(() => teams.id, { onDelete: "cascade" }),
        // Presented/normalized address — both nulled out (HMAC retained) by
        // a recipient privacy-erasure deletion; see PRD's retention section.
        recipientEmail: text("recipient_email"),
        normalizedRecipient: text("normalized_recipient"),
        recipientHash: text("recipient_hash").notNull(),
        hashKeyVersion: integer("hash_key_version").notNull(),
        reason: text("reason").notNull(),
        sourceEventId: uuid("source_event_id").references(
            () => emailDeliveryEvents.id,
            { onDelete: "set null" },
        ),
        active: boolean("active").notNull().default(true),
        firstSuppressedAt: timestamp("first_suppressed_at", {
            withTimezone: true,
        })
            .notNull()
            .defaultNow(),
        lastSuppressedAt: timestamp("last_suppressed_at", {
            withTimezone: true,
        })
            .notNull()
            .defaultNow(),
        releasedAt: timestamp("released_at", { withTimezone: true }),
        releasedBy: text("released_by").references(() => user.id, {
            onDelete: "set null",
        }),
        releaseReason: text("release_reason"),
        createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    },
    (table) => ({
        suppressionIdCheck: publicIdCheck(
            "email_suppressions_suppression_id_check",
            table.suppressionId,
            "sup",
        ),
        teamHashIdx: uniqueIndex(
            "email_suppressions_team_id_recipient_hash_idx",
        ).on(table.teamId, table.recipientHash),
        teamActiveIdx: index("email_suppressions_team_id_active_idx").on(
            table.teamId,
            table.active,
        ),
    }),
);

/** Append-only audit trail for every suppression create/reason-change/
 * release/reactivate — required so a permitted release is always
 * attributable (PRD acceptance criterion: "every permitted release is
 * audited"). Never updated or deleted by application code. */
export const emailSuppressionActions = pgTable(
    "email_suppression_actions",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        teamId: uuid("team_id")
            .notNull()
            .references(() => teams.id, { onDelete: "cascade" }),
        suppressionId: uuid("suppression_id")
            .notNull()
            .references(() => emailSuppressions.id, { onDelete: "cascade" }),
        sourceEventId: uuid("source_event_id").references(
            () => emailDeliveryEvents.id,
            { onDelete: "set null" },
        ),
        action: text("action").notNull(), // created | reason_changed | released | reactivated
        actorType: text("actor_type").notNull(), // system | workspace_user | sendlit_operator
        actorUserId: text("actor_user_id").references(() => user.id, {
            onDelete: "set null",
        }),
        explanation: text("explanation"),
        createdAt: timestamp("created_at", { withTimezone: true })
            .notNull()
            .defaultNow(),
    },
    (table) => ({
        suppressionActionsIdx: index(
            "email_suppression_actions_suppression_id_created_at_idx",
        ).on(table.suppressionId, table.createdAt),
    }),
);
