import {
    pgTable,
    uuid,
    text,
    timestamp,
    integer,
    bigint,
    boolean,
    doublePrecision,
    jsonb,
    index,
    uniqueIndex,
    check,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import type { CustomFields } from "@sendlit/api-contract";
import { genId, genPublicId } from "./id";

/** A `CHECK` enforcing that a public-id column always carries its resource's
 * prefix (`cnt_`, `seq_`, ...) — defense in depth alongside `genPublicId()`,
 * so a malformed value can never be inserted even by code that bypasses it
 * (a script, a future migration, direct SQL). */
function publicIdCheck(name: string, column: any, prefix: string) {
    // The pattern must be inlined as a literal, not a bound parameter —
    // drizzle-kit emits `CHECK` clauses verbatim into the migration SQL file,
    // which is replayed later with no params to bind against (`$1` would be
    // dangling, invalid SQL). `prefix` is always a trusted internal literal
    // (never user input), so `sql.raw` here is safe.
    return check(name, sql`${column} ~ ${sql.raw(`'^${prefix}_'`)}`);
}

/**
 * ID convention used across every table in this schema:
 *
 * - `id` is an internal-only UUIDv7 surrogate primary key. It is what every
 *   foreign key in this file references, and it is never returned by any
 *   REST/MCP response (see `utils/public.ts`). UUIDv7 keeps inserts roughly
 *   time-ordered, unlike UUIDv4/`gen_random_uuid()`, which scatters inserts
 *   randomly across the primary key's B-tree.
 * - `<domain>_id` (e.g. `contact_id`, `sequence_id`) is the public-facing
 *   identifier: `<prefix>_<24 random chars>`, generated by `genPublicId()`.
 *   It's the only ID ever exposed to API/MCP consumers, and the only one
 *   ever accepted back from them to address a row.
 *
 * Every foreign key in this file — including on the event/log tables
 * (`ongoing_sequences`, `email_deliveries`, `email_events`, `rules`) and
 * `contact_custom_field_values` — references the target row's internal `id`,
 * with `ON DELETE CASCADE`. Write paths that only have the public id on hand
 * (tracking pixels, rule processing) resolve public → internal id first.
 */

/**
 * A SendLit "account" is a login identity (one email = one account, OTP-based —
 * mirrors MediaLit's OAuth user model). An account owns/belongs to one or more
 * `teams`; a team — not the account — is the actual tenant/data-scope: every
 * other resource (contacts, templates, sequences, ESP config, API keys, ...) is
 * scoped by `teamId`, never `accountId`. This is what lets a single account
 * manage several independent "newsletters"/workspaces, and lets a consumer
 * (e.g. a multi-tenant app like CourseLit) provision one team per one of its
 * own tenants without their contacts/sending-identity/quota colliding.
 */
export const accounts = pgTable("accounts", {
    id: uuid("id").$defaultFn(genId).primaryKey(),
    email: text("email").notNull().unique(),
    name: text("name"),
    // Mail quota lives on the account (the billable identity), not on teams —
    // one account may own many teams, and its sending allowance is shared
    // across all of them. Checked/incremented via the team's owner account
    // (see `account/queries.ts`).
    dailyMailLimit: integer("daily_mail_limit").notNull().default(1000),
    monthlyMailLimit: integer("monthly_mail_limit").notNull().default(30000),
    dailyMailCount: integer("daily_mail_count").notNull().default(0),
    monthlyMailCount: integer("monthly_mail_count").notNull().default(0),
    countersResetAt: timestamp("counters_reset_at", {
        withTimezone: true,
    }).defaultNow(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

/** The tenant/data-scope boundary. Sending identity lives in `esp_configs`
 * and workspace settings in `settings` (both one row per team); mail
 * quota lives on the owning `accounts` row. `externalId` is an optional stable key for programmatic provisioning
 * by a consumer system (see `provisioning/routes.ts`) — e.g. `courselit:<domainId>` —
 * so a team can be found-or-created idempotently without relying on email
 * uniqueness (a consumer's own tenants may share an owner email).
 *
 * `teamId` is the public handle (`team_...`) returned to API/MCP/web
 * consumers and accepted back from them (route params, the
 * `X-Sendlit-Team-Id` header, provisioning responses). `id` remains
 * internal-only — every other table's `team_id` FK column still points at
 * it, and `req.teamId` (set by auth middleware) is always this internal id;
 * only the outermost edges (routes, the header, provisioning) ever see the
 * public `teamId` and translate it via `getTeamByTeamId`. */
export const teams = pgTable(
    "teams",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        teamId: text("team_id")
            .notNull()
            .unique()
            .$defaultFn(() => genPublicId("team")),
        name: text("name").notNull(),
        ownerAccountId: uuid("owner_account_id")
            .notNull()
            .references(() => accounts.id, { onDelete: "cascade" }),
        externalId: text("external_id").unique(),
        createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    },
    (table) => ({
        teamIdCheck: publicIdCheck("teams_team_id_check", table.teamId, "team"),
    }),
);

/** Which accounts can act on behalf of a team. Every team gets exactly one
 * `owner` row (its creator) today — member invitations are a follow-up — but
 * the shape already supports many accounts per team and many teams per account. */
export const teamMembers = pgTable(
    "team_members",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        teamId: uuid("team_id")
            .notNull()
            .references(() => teams.id, { onDelete: "cascade" }),
        accountId: uuid("account_id")
            .notNull()
            .references(() => accounts.id, { onDelete: "cascade" }),
        role: text("role").notNull().default("owner"), // 'owner' | 'member'
        createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
    },
    (table) => ({
        teamAccountIdx: uniqueIndex("team_members_team_id_account_id_idx").on(
            table.teamId,
            table.accountId,
        ),
    }),
);

export const authUser = pgTable("auth_user", {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    email: text("email").notNull().unique(),
    emailVerified: boolean("email_verified").notNull().default(false),
    image: text("image"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
});

export const authSession = pgTable(
    "auth_session",
    {
        id: text("id").primaryKey(),
        expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
        token: text("token").notNull().unique(),
        createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
        ipAddress: text("ip_address"),
        userAgent: text("user_agent"),
        userId: text("user_id")
            .notNull()
            .references(() => authUser.id, { onDelete: "cascade" }),
    },
    (table) => ({
        userIdIdx: index("auth_session_user_id_idx").on(table.userId),
    }),
);

export const authAccount = pgTable(
    "auth_account",
    {
        id: text("id").primaryKey(),
        accountId: text("account_id").notNull(),
        providerId: text("provider_id").notNull(),
        userId: text("user_id")
            .notNull()
            .references(() => authUser.id, { onDelete: "cascade" }),
        accessToken: text("access_token"),
        refreshToken: text("refresh_token"),
        idToken: text("id_token"),
        accessTokenExpiresAt: timestamp("access_token_expires_at", {
            withTimezone: true,
        }),
        refreshTokenExpiresAt: timestamp("refresh_token_expires_at", {
            withTimezone: true,
        }),
        scope: text("scope"),
        password: text("password"),
        createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
    },
    (table) => ({
        userIdIdx: index("auth_account_user_id_idx").on(table.userId),
    }),
);

export const authVerification = pgTable(
    "auth_verification",
    {
        id: text("id").primaryKey(),
        identifier: text("identifier").notNull(),
        value: text("value").notNull(),
        expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
        createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
    },
    (table) => ({
        identifierIdx: index("auth_verification_identifier_idx").on(
            table.identifier,
        ),
    }),
);

export const jwks = pgTable("auth_jwks", {
    id: text("id").primaryKey(),
    publicKey: text("public_key").notNull(),
    privateKey: text("private_key").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }),
});

export const authOAuthClient = pgTable(
    "auth_oauth_client",
    {
        id: text("id").primaryKey(),
        clientId: text("client_id").notNull().unique(),
        clientSecret: text("client_secret"),
        disabled: boolean("disabled").default(false),
        skipConsent: boolean("skip_consent"),
        enableEndSession: boolean("enable_end_session"),
        subjectType: text("subject_type"),
        scopes: text("scopes").array(),
        userId: text("user_id").references(() => authUser.id, {
            onDelete: "cascade",
        }),
        createdAt: timestamp("created_at", { withTimezone: true }),
        updatedAt: timestamp("updated_at", { withTimezone: true }),
        name: text("name"),
        uri: text("uri"),
        icon: text("icon"),
        contacts: text("contacts").array(),
        tos: text("tos"),
        policy: text("policy"),
        softwareId: text("software_id"),
        softwareVersion: text("software_version"),
        softwareStatement: text("software_statement"),
        redirectUris: text("redirect_uris").array().notNull(),
        postLogoutRedirectUris: text("post_logout_redirect_uris").array(),
        tokenEndpointAuthMethod: text("token_endpoint_auth_method"),
        grantTypes: text("grant_types").array(),
        responseTypes: text("response_types").array(),
        public: boolean("public"),
        type: text("type"),
        requirePKCE: boolean("require_pkce"),
        referenceId: text("reference_id"),
        metadata: jsonb("metadata"),
    },
    (table) => ({
        userIdIdx: index("auth_oauth_client_user_id_idx").on(table.userId),
    }),
);

export const authOAuthRefreshToken = pgTable(
    "auth_oauth_refresh_token",
    {
        id: text("id").primaryKey(),
        token: text("token").notNull().unique(),
        clientId: text("client_id")
            .notNull()
            .references(() => authOAuthClient.clientId, {
                onDelete: "cascade",
            }),
        sessionId: text("session_id").references(() => authSession.id, {
            onDelete: "set null",
        }),
        userId: text("user_id")
            .notNull()
            .references(() => authUser.id, { onDelete: "cascade" }),
        referenceId: text("reference_id"),
        expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
        createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
        revoked: timestamp("revoked", { withTimezone: true }),
        authTime: timestamp("auth_time", { withTimezone: true }),
        scopes: text("scopes").array().notNull(),
    },
    (table) => ({
        clientIdIdx: index("auth_oauth_refresh_token_client_id_idx").on(
            table.clientId,
        ),
        sessionIdIdx: index("auth_oauth_refresh_token_session_id_idx").on(
            table.sessionId,
        ),
        userIdIdx: index("auth_oauth_refresh_token_user_id_idx").on(
            table.userId,
        ),
    }),
);

export const authOAuthAccessToken = pgTable(
    "auth_oauth_access_token",
    {
        id: text("id").primaryKey(),
        token: text("token").notNull().unique(),
        clientId: text("client_id")
            .notNull()
            .references(() => authOAuthClient.clientId, {
                onDelete: "cascade",
            }),
        sessionId: text("session_id").references(() => authSession.id, {
            onDelete: "set null",
        }),
        userId: text("user_id").references(() => authUser.id, {
            onDelete: "cascade",
        }),
        referenceId: text("reference_id"),
        refreshId: text("refresh_id").references(
            () => authOAuthRefreshToken.id,
            { onDelete: "set null" },
        ),
        expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
        createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
        scopes: text("scopes").array().notNull(),
    },
    (table) => ({
        clientIdIdx: index("auth_oauth_access_token_client_id_idx").on(
            table.clientId,
        ),
        sessionIdIdx: index("auth_oauth_access_token_session_id_idx").on(
            table.sessionId,
        ),
        userIdIdx: index("auth_oauth_access_token_user_id_idx").on(
            table.userId,
        ),
        refreshIdIdx: index("auth_oauth_access_token_refresh_id_idx").on(
            table.refreshId,
        ),
    }),
);

export const authOAuthConsent = pgTable(
    "auth_oauth_consent",
    {
        id: text("id").primaryKey(),
        clientId: text("client_id")
            .notNull()
            .references(() => authOAuthClient.clientId, {
                onDelete: "cascade",
            }),
        userId: text("user_id").references(() => authUser.id, {
            onDelete: "cascade",
        }),
        referenceId: text("reference_id"),
        scopes: text("scopes").array().notNull(),
        createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
    },
    (table) => ({
        clientIdIdx: index("auth_oauth_consent_client_id_idx").on(
            table.clientId,
        ),
        userIdIdx: index("auth_oauth_consent_user_id_idx").on(table.userId),
    }),
);

/** A key authenticates as exactly one team — never an account directly — so a
 * team can hand out several independently-revocable keys (e.g. one for a
 * CourseLit integration, another for a Zapier zap) without any of them being
 * able to see another team the owning account belongs to.
 *
 * The secret itself (`sl_live_...`) is never stored — only its SHA-256
 * (`keyHash`, what auth looks up) and its first few characters (`keyPrefix`,
 * for display in key lists). See `apikey/secret.ts`. `id` doubles as this
 * row's own public handle (used to list/revoke a specific key) — a separate
 * `<domain>_id` isn't needed since `keyPrefix`/`keyHash` already solve the
 * "identify a key without exposing its secret" problem this convention is for. */
export const apiKeys = pgTable("api_keys", {
    id: uuid("id").$defaultFn(genId).primaryKey(),
    teamId: uuid("team_id")
        .notNull()
        .references(() => teams.id, { onDelete: "cascade" }),
    keyHash: text("key_hash").notNull().unique(),
    keyPrefix: text("key_prefix").notNull(),
    name: text("name"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

/** A contact is a recipient/subscriber. Equivalent of CourseLit's `User` model,
 * stripped of everything course/product related. `contactId` is the public
 * handle (`cnt_...`); `id` is internal-only. */
export const contacts = pgTable(
    "contacts",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        teamId: uuid("team_id")
            .notNull()
            .references(() => teams.id, { onDelete: "cascade" }),
        contactId: text("contact_id")
            .notNull()
            .unique()
            .$defaultFn(() => genPublicId("cnt")),
        email: text("email").notNull(),
        name: text("name"),
        subscribed: boolean("subscribed").notNull().default(true),
        // Intentionally kept alongside `contact_custom_field_values`: this
        // jsonb is the denormalized public read/render snapshot (API
        // responses, merge tags), while the table is the indexed store used
        // for segmentation queries.
        customFields: jsonb("custom_fields")
            .$type<CustomFields>()
            .notNull()
            .default({}),
        tags: text("tags").array().notNull().default([]),
        unsubscribeToken: text("unsubscribe_token").notNull().unique(),
        createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    },
    (table) => ({
        teamEmailIdx: uniqueIndex("contacts_team_id_email_idx").on(
            table.teamId,
            table.email,
        ),
        contactIdCheck: publicIdCheck(
            "contacts_contact_id_check",
            table.contactId,
            "cnt",
        ),
    }),
);

/** Indexed custom field values for scalable generic contact segmentation.
 * `contacts.customFields` remains the public/read snapshot; this table stores
 * one row per scalar value, including each element of scalar arrays.
 * `contactId` here references the contact's *internal* id. */
export const contactCustomFieldValues = pgTable(
    "contact_custom_field_values",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        teamId: uuid("team_id")
            .notNull()
            .references(() => teams.id, { onDelete: "cascade" }),
        contactId: uuid("contact_id")
            .notNull()
            .references(() => contacts.id, { onDelete: "cascade" }),
        key: text("key").notNull(),
        valueType: text("value_type").notNull(), // string | number | boolean | date
        valueText: text("value_text"),
        valueNumber: doublePrecision("value_number"),
        valueBoolean: boolean("value_boolean"),
        valueDate: timestamp("value_date", { withTimezone: true }),
        createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    },
    (table) => ({
        contactKeyIdx: index("contact_custom_field_values_contact_key_idx").on(
            table.teamId,
            table.contactId,
            table.key,
        ),
        textLookupIdx: index("contact_custom_field_values_text_lookup_idx").on(
            table.teamId,
            table.key,
            table.valueText,
        ),
        numberLookupIdx: index(
            "contact_custom_field_values_number_lookup_idx",
        ).on(table.teamId, table.key, table.valueNumber),
        booleanLookupIdx: index(
            "contact_custom_field_values_boolean_lookup_idx",
        ).on(table.teamId, table.key, table.valueBoolean),
        dateLookupIdx: index("contact_custom_field_values_date_lookup_idx").on(
            table.teamId,
            table.key,
            table.valueDate,
        ),
    }),
);

export const emailTemplates = pgTable(
    "email_templates",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        teamId: uuid("team_id")
            .notNull()
            .references(() => teams.id, { onDelete: "cascade" }),
        templateId: text("template_id")
            .notNull()
            .unique()
            .$defaultFn(() => genPublicId("tpl")),
        title: text("title").notNull(),
        // { content: EmailBlock[], style: EmailStyle, meta: EmailMeta } — see @sendlit/email-editor
        content: jsonb("content").notNull(),
        createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    },
    (table) => ({
        teamTitleIdx: uniqueIndex("email_templates_team_id_title_idx").on(
            table.teamId,
            table.title,
        ),
        templateIdCheck: publicIdCheck(
            "email_templates_template_id_check",
            table.templateId,
            "tpl",
        ),
    }),
);

/** A saved, named, reusable contact filter — the persisted form of the
 * `ContactFilterWithAggregator` shape (see `contacts/segment.ts`) that
 * `sequences.filter`/`excludeFilter` already store inline per-broadcast. This
 * table lets a team build a filter once and reuse it by name instead of
 * re-building it for every broadcast/sequence. */
export const segments = pgTable(
    "segments",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        teamId: uuid("team_id")
            .notNull()
            .references(() => teams.id, { onDelete: "cascade" }),
        segmentId: text("segment_id")
            .notNull()
            .unique()
            .$defaultFn(() => genPublicId("seg")),
        name: text("name").notNull(),
        // ContactFilterWithAggregator — see contacts/segment.ts
        filter: jsonb("filter").notNull(),
        createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    },
    (table) => ({
        teamNameIdx: uniqueIndex("segments_team_id_name_idx").on(
            table.teamId,
            table.name,
        ),
        segmentIdCheck: publicIdCheck(
            "segments_segment_id_check",
            table.segmentId,
            "seg",
        ),
    }),
);

/** Per-team ESP (Email Service Provider) transport configuration. One row
 * per team — when present, outgoing mail for that team is sent through
 * this SMTP connection; teams without an ESP cannot send campaign mail.
 * `encryptedSecret` holds an AES-256-GCM encrypted JSON blob (see
 * `utils/secret-crypto.ts`) and is never returned to API clients. This is
 * also the only place sender identity (`fromName`/`fromEmail`) lives —
 * addressed publicly as the per-team `/settings/esp` singleton, so its
 * internal `id` is never exposed (no `<domain>_id` needed). */
export const espConfigs = pgTable("esp_configs", {
    id: uuid("id").$defaultFn(genId).primaryKey(),
    teamId: uuid("team_id")
        .notNull()
        .unique()
        .references(() => teams.id, { onDelete: "cascade" }),
    provider: text("provider").notNull().default("smtp"),
    host: text("host").notNull(),
    port: integer("port").notNull().default(587),
    secure: boolean("secure").notNull().default(false),
    username: text("username"),
    encryptedSecret: text("encrypted_secret"),
    fromName: text("from_name"),
    fromEmail: text("from_email"),
    lastTestedAt: timestamp("last_tested_at", { withTimezone: true }),
    lastTestStatus: text("last_test_status"), // success | failed
    lastTestError: text("last_test_error"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

/** Per-team general workspace settings ("settings.general") — a per-team
 * singleton like `esp_configs`, addressed via the team (`/settings/general`),
 * so no public `<domain>_id` is needed. `mailingAddress` is the physical
 * postal address rendered in email footers (CAN-SPAM/GDPR requirement). */
export const settings = pgTable("settings", {
    id: uuid("id").$defaultFn(genId).primaryKey(),
    teamId: uuid("team_id")
        .notNull()
        .unique()
        .references(() => teams.id, { onDelete: "cascade" }),
    mailingAddress: text("mailing_address"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

/** A broadcast (one-off, `type = 'broadcast'`) or a sequence (multi-step,
 * `type = 'sequence'`) — same shape as CourseLit's `Sequence` model. */
export const sequences = pgTable(
    "sequences",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        teamId: uuid("team_id")
            .notNull()
            .references(() => teams.id, { onDelete: "cascade" }),
        sequenceId: text("sequence_id")
            .notNull()
            .unique()
            .$defaultFn(() => genPublicId("seq")),
        type: text("type").notNull(), // 'broadcast' | 'sequence'
        title: text("title").notNull().default(""),
        status: text("status").notNull().default("draft"), // draft|active|paused|completed
        // Which sending identity ("outbox") this sequence uses. Internal-only
        // — never exposed via REST/MCP (esp_configs has no public id; it's a
        // per-team singleton). null = send via the team's ESP config;
        // non-null = send via that esp config's fromName/fromEmail.
        outboxId: uuid("outbox_id").references(() => espConfigs.id, {
            onDelete: "set null",
        }),
        triggerType: text("trigger_type"), // Constants.EventType
        triggerData: text("trigger_data"),
        // UserFilterWithAggregator — see contacts/segment.ts
        filter: jsonb("filter"),
        excludeFilter: jsonb("exclude_filter"),
        emailsOrder: text("emails_order").array().notNull().default([]),
        entrants: text("entrants").array().notNull().default([]),
        // { broadcast: { sentAt, lockedAt }, sequence: { subscribers, unsubscribers, failed } }
        report: jsonb("report").notNull().default({}),
        createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    },
    (table) => ({
        sequenceIdCheck: publicIdCheck(
            "sequences_sequence_id_check",
            table.sequenceId,
            "seq",
        ),
    }),
);

/** A structural child of exactly one `sequences` row — never addressed
 * independently, so `sequenceId` references the parent's internal `id`
 * (unlike the event/log tables below, which store the public id). `emailId`
 * is this row's own public handle within that sequence. */
export const sequenceEmails = pgTable(
    "sequence_emails",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        sequenceId: uuid("sequence_id")
            .notNull()
            .references(() => sequences.id, { onDelete: "cascade" }),
        emailId: text("email_id")
            .notNull()
            .$defaultFn(() => genPublicId("email")),
        subject: text("subject").notNull(),
        // { content: EmailBlock[], style: EmailStyle, meta: EmailMeta }
        content: jsonb("content").notNull(),
        delayInMillis: bigint("delay_in_millis", { mode: "number" })
            .notNull()
            .default(86400000),
        published: boolean("published").notNull().default(false),
        templateId: text("template_id"),
        actionType: text("action_type"), // tag:add | tag:remove
        actionData: jsonb("action_data"),
        createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    },
    (table) => ({
        sequenceEmailIdx: uniqueIndex(
            "sequence_emails_sequence_id_email_id_idx",
        ).on(table.sequenceId, table.emailId),
        emailIdCheck: publicIdCheck(
            "sequence_emails_email_id_check",
            table.emailId,
            "email",
        ),
    }),
);

/** A scheduled trigger for a sequence — e.g. "fire DATE_OCCURRED for broadcast X at
 * time T", processed by `automation/process-rules.ts`. Not exposed via any
 * REST/MCP route today. */
export const rules = pgTable(
    "rules",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        teamId: uuid("team_id")
            .notNull()
            .references(() => teams.id, { onDelete: "cascade" }),
        ruleId: text("rule_id")
            .notNull()
            .unique()
            .$defaultFn(() => genPublicId("rule")),
        event: text("event").notNull(), // Constants.EventType
        sequenceId: uuid("sequence_id")
            .notNull()
            .references(() => sequences.id, { onDelete: "cascade" }),
        eventDateInMillis: bigint("event_date_in_millis", { mode: "number" }),
        eventData: text("event_data"),
        createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    },
    (table) => ({
        ruleIdCheck: publicIdCheck("rules_rule_id_check", table.ruleId, "rule"),
    }),
);

/** One row per (sequence, contact) currently being delivered. Processed by
 * `automation/process-ongoing-sequence.ts`. */
export const ongoingSequences = pgTable(
    "ongoing_sequences",
    {
        id: uuid("id").$defaultFn(genId).primaryKey(),
        teamId: uuid("team_id")
            .notNull()
            .references(() => teams.id, { onDelete: "cascade" }),
        sequenceId: uuid("sequence_id")
            .notNull()
            .references(() => sequences.id, { onDelete: "cascade" }),
        contactId: uuid("contact_id")
            .notNull()
            .references(() => contacts.id, { onDelete: "cascade" }),
        nextEmailScheduledTime: bigint("next_email_scheduled_time", {
            mode: "number",
        }).notNull(),
        retryCount: integer("retry_count").notNull().default(0),
        sentEmailIds: text("sent_email_ids").array().notNull().default([]),
        createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    },
    (table) => ({
        sequenceContactIdx: uniqueIndex(
            "ongoing_sequences_sequence_id_contact_id_idx",
        ).on(table.sequenceId, table.contactId),
        // The 60s due-poll (`getDueOngoingSequences`) filters on this column.
        nextScheduledIdx: index(
            "ongoing_sequences_next_email_scheduled_time_idx",
        ).on(table.nextEmailScheduledTime),
    }),
);

export const emailDeliveries = pgTable("email_deliveries", {
    id: uuid("id").$defaultFn(genId).primaryKey(),
    teamId: uuid("team_id")
        .notNull()
        .references(() => teams.id, { onDelete: "cascade" }),
    sequenceId: uuid("sequence_id")
        .notNull()
        .references(() => sequences.id, { onDelete: "cascade" }),
    contactId: uuid("contact_id")
        .notNull()
        .references(() => contacts.id, { onDelete: "cascade" }),
    emailId: uuid("email_id")
        .notNull()
        .references(() => sequenceEmails.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export const emailEvents = pgTable("email_events", {
    id: uuid("id").$defaultFn(genId).primaryKey(),
    teamId: uuid("team_id")
        .notNull()
        .references(() => teams.id, { onDelete: "cascade" }),
    sequenceId: uuid("sequence_id")
        .notNull()
        .references(() => sequences.id, { onDelete: "cascade" }),
    contactId: uuid("contact_id")
        .notNull()
        .references(() => contacts.id, { onDelete: "cascade" }),
    emailId: uuid("email_id")
        .notNull()
        .references(() => sequenceEmails.id, { onDelete: "cascade" }),
    action: text("action").notNull(), // open | click | bounce
    link: text("link"),
    linkIndex: integer("link_index"),
    bounceType: text("bounce_type"), // hard | soft
    bounceReason: text("bounce_reason"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});
